= Overview

:toc:

[cloud-intro]

== Module: Cloud Introduction (theory-block I)

* What is Cloud Computing? Encounters in everyday life and history
* Characteristic, advantages & challenges
* Terminology - public, private, hybrid, dedicated
* Abstraction layers - IaaS, PaaS, FaaS, SaaS
* Overview - Hypervisors, virtual machines, containers and orchestration
* Overview - Global cloud service providers (CSPs), technologies and corresponding offerings

=== Objectives and exercises 
_The student is able to describe cloud computing in own words and list examples for offerings, topologies and technologies. Includes ability to differentiate between different abstraction layers and knowledge how those layers and according technologies interact with each other. No exercises in this module_

=== Links

 * https://landscape.cncf.io/
 * https://www.cncf.io/wp-content/uploads/2020/11/CNCF_Survey_Report_2020.pdf

== Module: Spring Boot Introduction

* Background: Spring Framework - History & components
* Spring <- -> Spring Boot
* Spring Initializr (start.spring.io) & starter dependencies
* Basic project structure (folders, configuration ..)
* "Hello, World!" example explained
* Basic logging and testing
* Using Actuator

=== Objectives
_The student is able to build and configure an own Spring Boot application from scratch with the IDE of choice. The exercise is to build an own "Hello, World!" application that exposes various REST endpoints and is able to execute CRUD operations on the state of the application. Optional: Add logging and testing, configure Actuator._

=== Exercises

* Build a simple Spring Boot Microservice with the following starter dependencies: Web, Actuator
* Run the microservice and test the endpoint /actuator/health and /actuator/info
* Annotate the Microservice with @RestController and implement a "Hello, World!" method, which responds to an HTTP GET request.
* Add some basic "functionality" to make the service react to HTTP GET, POST, PUT and DELETE calls (e.g. modify an internal list)
* Change the configuration to make the server run on port 8081 instead of 8080

== Module: Containers

* What are containers and how do they work
* Containers vs. VMs 
* History of containers and rise of Docker
* Docker concepts: daemon, hub, dockerfile, CLI
* Multi-container handling with docker-compose
* Limitations and problems with containers

=== Objectives and exercises
_The student understands the concepts and use cases of container technology and is able to describe them. The first exercise is to pull sample images from an image registry (e.g. Docker Hub) and interact with them (run, expose port, execute shell, cleanup etc). After that the student can show how to build a custom image via Dockerfile and push it to a registry for others to access. Optional: Take the sample application from module "Spring Boot Intro", put it into a container image and run it._

== Module: Persistence

* Spring Data
* Concept of entities and repositories
* JPA and JDBC basics
* H2, PostgeSQL, MySQL - configuration via Spring Boot
* Running databases as Docker images
* //TODO, Spring Data JDBC, SQL and noSQL examples

=== Objectives and exercises
_The student is able to build a Spring Boot application (or extend an existing one) with Spring Data configuration. The exercise is to create an application, which performs CRUD operations on a database backend. The database can either be in-memory (H2) or a (containerized) PostgreSQL. Optional: Provide a docker-compose file to stand up a multi-container environment with application and database._
